# Generated by Django 5.0.7 on 2024-07-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.usercourse'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(),
        ),
    ]
